<?php
/**
	Eleanor CMS © 2014
	http://eleanor-cms.ru
	info@eleanor-cms.ru
*/
namespace CMS;
defined('CMS\STARTED')||die;

$lang=Eleanor::$Language->Load(DIR.'admin/translation/users-groups-*.php');
$IntSave=function($control)
{
	return abs((int)$control['value']);
};

return[
	$lang['global-rights'],
	'is_admin'=>[
		'title'=>$lang['is-admin'],
		'descr'=>$lang['is-admin_'],
		'type'=>'check',
		'options'=>[
			'extra'=>['class'=>'need-tabindex','onclick'=>"if(this.checked) return confirm('{$lang['are_you_sure']}')"],
		],
	],
	'banned'=>[
		'title'=>$lang['ban'],
		'descr'=>$lang['ban_'],
		'type'=>'check',
		'options'=>[
			'extra'=>['class'=>'need-tabindex'],
		],
	],
	'captcha'=>[
		'title'=>$lang['captcha'],
		'descr'=>$lang['captcha_'],
		'type'=>'check',
		'options'=>[
			'extra'=>['class'=>'need-tabindex'],
		],
	],
	'moderate'=>[
		'title'=>$lang['moderate'],
		'descr'=>$lang['moderate_'],
		'type'=>'check',
		'options'=>[
			'extra'=>['class'=>'need-tabindex'],
		],
	],
	'closed_site_access'=>[
		'title'=>$lang['closed-site'],
		'descr'=>'',
		'type'=>'check',
		'options'=>[
			'extra'=>['class'=>'need-tabindex'],
		],
	],
	
	$lang['limits'],
	'flood_limit'=>[
		'title'=>$lang['flood_limit'],
		'descr'=>$lang['flood_limit_'],
		'save'=>$IntSave,
		'type'=>'input',
		'default'=>0,
		'label-for'=>'flood-limit',
		'options'=>[
			'type'=>'number',
			'extra'=>['class'=>'need-tabindex','id'=>'flood-limit'],
		],
	],
	'search_limit'=>[
		'title'=>$lang['search_limit'],
		'descr'=>$lang['search_limit_'],
		'save'=>$IntSave,
		'type'=>'input',
		'default'=>0,
		'label-for'=>'search-limit',
		'options'=>[
			'type'=>'number',
			'extra'=>['class'=>'need-tabindex','id'=>'search-limit'],
		],
	],
	'max_upload'=>[
		'title'=>$lang['max_size'],
		'descr'=>$lang['max_size_'],
		'type'=>'input',
		'default'=>0,
		'label-for'=>'max-upload',
		'options'=>[
			'type'=>'number',
			'extra'=>['class'=>'need-tabindex','id'=>'max-upload'],
		],
	],
];